[2023-11-06T17:04:55.429+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yahoo_finance_elt_pipeline_v03.extract_data_task manual__2023-11-06T17:04:42.811725+00:00 [queued]>
[2023-11-06T17:04:55.470+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yahoo_finance_elt_pipeline_v03.extract_data_task manual__2023-11-06T17:04:42.811725+00:00 [queued]>
[2023-11-06T17:04:55.472+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-06T17:04:55.538+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data_task> on 2023-11-06 17:04:42.811725+00:00
[2023-11-06T17:04:55.562+0000] {standard_task_runner.py:57} INFO - Started process 897 to run task
[2023-11-06T17:04:55.581+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yahoo_finance_elt_pipeline_v03', 'extract_data_task', 'manual__2023-11-06T17:04:42.811725+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/yahoo_elt_pipeline.py', '--cfg-path', '/tmp/tmpxhwzw7pc']
[2023-11-06T17:04:55.591+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask extract_data_task
[2023-11-06T17:04:55.853+0000] {task_command.py:416} INFO - Running <TaskInstance: yahoo_finance_elt_pipeline_v03.extract_data_task manual__2023-11-06T17:04:42.811725+00:00 [running]> on host a5d58a06784e
[2023-11-06T17:04:56.834+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mbahraoui' AIRFLOW_CTX_DAG_ID='yahoo_finance_elt_pipeline_v03' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T17:04:42.811725+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-06T17:04:42.811725+00:00'
[2023-11-06T17:05:01.269+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:05:01.296+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yahoo_elt_pipeline.py", line 40, in extract_data
    stock_data_df = stock_data_df.append(data, ignore_index=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
[2023-11-06T17:05:01.387+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yahoo_finance_elt_pipeline_v03, task_id=extract_data_task, execution_date=20231106T170442, start_date=20231106T170455, end_date=20231106T170501
[2023-11-06T17:05:01.451+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task extract_data_task ('DataFrame' object has no attribute 'append'; 897)
[2023-11-06T17:05:01.518+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T17:05:01.626+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
