[2023-11-07T01:06:02.973+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yahoo_finance_elt_pipeline_v11.print_structure manual__2023-11-07T01:05:40.482147+00:00 [queued]>
[2023-11-07T01:06:03.094+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yahoo_finance_elt_pipeline_v11.print_structure manual__2023-11-07T01:05:40.482147+00:00 [queued]>
[2023-11-07T01:06:03.120+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-07T01:06:03.402+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): print_structure> on 2023-11-07 01:05:40.482147+00:00
[2023-11-07T01:06:03.444+0000] {standard_task_runner.py:57} INFO - Started process 296 to run task
[2023-11-07T01:06:03.467+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yahoo_finance_elt_pipeline_v11', 'print_structure', 'manual__2023-11-07T01:05:40.482147+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/yahoo_elt_pipeline.py', '--cfg-path', '/tmp/tmpe6ec83ye']
[2023-11-07T01:06:03.502+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask print_structure
[2023-11-07T01:06:04.304+0000] {task_command.py:416} INFO - Running <TaskInstance: yahoo_finance_elt_pipeline_v11.print_structure manual__2023-11-07T01:05:40.482147+00:00 [running]> on host 57084f613782
[2023-11-07T01:06:04.950+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mbahraoui' AIRFLOW_CTX_DAG_ID='yahoo_finance_elt_pipeline_v11' AIRFLOW_CTX_TASK_ID='print_structure' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T01:05:40.482147+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T01:05:40.482147+00:00'
[2023-11-07T01:06:04.961+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yahoo_elt_pipeline.py", line 27, in print_file_structure
    for item in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: ''
[2023-11-07T01:06:05.063+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yahoo_finance_elt_pipeline_v11, task_id=print_structure, execution_date=20231107T010540, start_date=20231107T010602, end_date=20231107T010605
[2023-11-07T01:06:05.218+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task print_structure ([Errno 2] No such file or directory: ''; 296)
[2023-11-07T01:06:05.364+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T01:06:05.471+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
